import { useEffect, useState } from 'react'; import api, { errMsg } from '../services/api'; import { useApp } from '../context/AppContext'; import { money } from '../components/ProductCard';
function Crud({ rows, fields, show, save, remove, title }) {
  const { notify } = useApp(); const [f, setF] = useState(null);
  const prefill = (r) => ({ ...Object.fromEntries(fields.map(([k, , t]) => [k, t === 'list' ? (r[k] || []).join(', ') : t === 'date' ? String(r[k] || '').slice(0, 10) : r[k] ?? ''])), _id: r._id });
  const edit = (r) => setF(r ? prefill(r) : {});
  const submit = async () => { const b = {}; fields.forEach(([k, , t]) => { const v = f[k]; if (v === '' || v == null) return; b[k] = t === 'number' ? +v : t === 'list' ? String(v).split(',').map((s) => s.trim()).filter(Boolean) : t === 'bool' ? v === true || v === 'true' : v; });
    try { await save(f._id, b); setF(null); notify('Saved'); } catch (e) { notify(errMsg(e), 'err'); } };
  return (<div className="card mt"><div className="row between"><h3>{title} ({rows.length})</h3><button className="btn sm" onClick={() => edit(null)}>+ Add</button></div>
    {f && <div className="mt"><div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))' }}>{fields.map(([k, l, t, opts]) => t === 'select' || t === 'bool' ? <select key={k} value={String(f[k] ?? '')} onChange={(e) => setF({ ...f, [k]: e.target.value })}><option value="">{l}</option>{(t === 'bool' ? [['true', 'Active'], ['false', 'Inactive']] : opts).map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select> : <input key={k} type={t === 'number' ? 'number' : t === 'date' ? 'date' : 'text'} placeholder={l} title={l} value={f[k] ?? ''} onChange={(e) => setF({ ...f, [k]: e.target.value })} />)}</div>
      <div className="row mt"><button className="btn sm" onClick={submit}>Save</button><button className="btn ghost sm" onClick={() => setF(null)}>Cancel</button></div></div>}
    <div style={{ overflowX: 'auto' }}>{rows.map((r) => <div key={r._id} className="tx"><span style={{ flex: 1 }}>{show(r)}</span><button className="link" onClick={() => edit(r)}>Edit</button>{remove && <button className="link bad" style={{ marginLeft: 12 }} onClick={() => remove(r._id)}>Delete</button>}</div>)}</div></div>);
}
export default function Admin() {
  const { notify } = useApp(); const [tab, setTab] = useState('Dashboard'); const [s, setS] = useState(null); const [prods, setProds] = useState([]); const [stores, setStores] = useState([]); const [coupons, setCoupons] = useState([]);
  const [f, setF] = useState({ name: '', store: '', product: '', discount: '20%', audience: 'College students', tone: 'Exciting', event: '' }); const [out, setOut] = useState(null); const [busy, setBusy] = useState(false);
  const load = () => { api.get('/admin/stats').then((r) => setS(r.data)).catch((e) => notify(errMsg(e), 'err')); api.get('/products', { params: { limit: 100 } }).then((r) => setProds(r.data.items)).catch(() => {}); api.get('/admin/stores').then((r) => setStores(r.data)).catch(() => {}); api.get('/admin/coupons').then((r) => setCoupons(r.data)).catch(() => {}); }; useEffect(load, []);
  const upsert = (path) => async (id, b) => { await (id ? api.put(`${path}/${id}`, b) : api.post(path, b)); load(); };
  const del = async (id) => { if (!window.confirm('Delete this product?')) return; try { await api.delete(`/products/${id}`); notify('Product deleted'); load(); } catch (e) { notify(errMsg(e), 'err'); } };
  const gen = async () => { setBusy(true); try { setOut((await api.post('/ai/generate-campaign', f)).data); } catch (e) { notify(errMsg(e), 'err'); } finally { setBusy(false); } };
  const so = stores.map((x) => [x._id, x.name]); const max = Math.max(...(s?.days || []).map((d) => d.revenue), 1);
  return (<div className="wrap sec"><h1>Admin</h1><div className="tabs mt">{['Dashboard', 'Products', 'Stores', 'Coupons', 'AI Marketing'].map((t) => <button key={t} className={tab === t ? 'on' : ''} onClick={() => setTab(t)}>{t}</button>)}</div>
    {tab === 'Dashboard' && (s ? <><div className="grid g4">{[['Total Revenue', money(s.revenue)], ['Total Orders', s.orders], ['Total Users', s.users], ['Active Coupons', s.coupons], ['Points Issued', s.issued], ['Points Redeemed', s.redeemed]].map(([a, b]) => <div key={a} className="card"><small className="muted">{a}</small><h2>{b}</h2></div>)}</div>
      <div className="card mt"><h3>Revenue — last 7 days</h3><div className="bars">{s.days.map((d) => <div key={d.key}><i style={{ height: `${(d.revenue / max) * 100}%` }} title={money(d.revenue)} /><small>{d.day}</small></div>)}</div></div>
      <div className="card mt"><h3>Recent Orders</h3>{s.recent.map((o) => <div key={o._id} className="tx"><span>{o.orderNumber}</span><span className="muted">{o.status}</span><b>{money(o.totalAmount)}</b></div>)}{!s.recent.length && <p className="muted">No orders yet.</p>}</div></> : <div className="sk" />)}
    {tab === 'Products' && <Crud title="Products" rows={prods} remove={del} save={upsert('/products')} show={(p) => `${p.name} · ${money(p.price)} · stock ${p.stock}`}
      fields={[['name', 'Name'], ['brand', 'Brand'], ['price', 'Price', 'number'], ['originalPrice', 'Original price', 'number'], ['category', 'Category'], ['store', 'Store', 'select', so], ['stock', 'Stock', 'number'], ['rating', 'Rating', 'number'], ['images', 'Image URLs (comma separated)', 'list'], ['tags', 'Tags (comma separated)', 'list'], ['description', 'Description']]} />}
    {tab === 'Stores' && <Crud title="Stores" rows={stores} save={upsert('/stores')} show={(x) => `${x.name} · ${x.category} · ${x.isActive ? 'Active' : 'Inactive'}`}
      fields={[['name', 'Store name'], ['category', 'Category'], ['description', 'Description'], ['logo', 'Logo URL'], ['banner', 'Banner URL'], ['isActive', 'Status', 'bool']]} />}
    {tab === 'Coupons' && <Crud title="Coupons" rows={coupons} save={upsert('/admin/coupons')} show={(c) => `${c.code} · ${c.discountType === 'percent' ? c.discountValue + '%' : '₹' + c.discountValue} · used ${c.usedCount}/${c.usageLimit || '∞'} · ${!c.isActive ? 'Disabled' : new Date(c.expiryDate) < new Date() ? 'Expired' : 'Active'}`}
      fields={[['code', 'Code'], ['discountType', 'Discount type', 'select', [['percent', 'Percent'], ['flat', 'Flat ₹']]], ['discountValue', 'Discount value', 'number'], ['minimumOrder', 'Minimum order', 'number'], ['maximumDiscount', 'Max discount', 'number'], ['usageLimit', 'Usage limit (0 = unlimited)', 'number'], ['expiryDate', 'Expiry date', 'date'], ['store', 'Applicable store', 'select', so], ['category', 'Applicable category'], ['isActive', 'Status', 'bool']]} />}
    {tab === 'AI Marketing' && <div className="card"><h3>AI Marketing Studio (Gemini)</h3><div className="grid mt" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))' }}>{[['name', 'Campaign name'], ['store', 'Store'], ['product', 'Product'], ['discount', 'Discount'], ['audience', 'Audience'], ['tone', 'Tone'], ['event', 'Festival/Event']].map(([k, l]) => <input key={k} placeholder={l} value={f[k]} onChange={(e) => setF({ ...f, [k]: e.target.value })} />)}</div>
      <button className="btn mt" disabled={busy} onClick={gen}>{busy ? 'Generating…' : out ? 'Regenerate' : 'Generate Campaign'}</button>{out && <div className="mt">{Object.entries(out).map(([k, v]) => <p key={k}><b>{k}:</b> {String(v)}</p>)}<button className="btn ghost sm" onClick={() => navigator.clipboard?.writeText(Object.values(out).join('\n'))}>Copy</button></div>}</div>}</div>);
}
