import { useEffect, useState } from 'react'; import { Link } from 'react-router-dom'; import api, { errMsg } from '../services/api'; import { useApp } from '../context/AppContext';
const R = [['r50', '₹50 Shopping Reward', 'Flat ₹50 off your next order', 500, '50'], ['r100', '₹100 Shopping Reward', 'Flat ₹100 off your next order', 1000, '100'], ['ship', 'Free Shipping', 'Covers the delivery fee once', 300, 'FREE'], ['p10', '10% OFF Coupon', '10% off, up to ₹500', 700, '10%']];
const LV = [['Bronze', 0], ['Silver', 1000], ['Gold', 3000], ['Platinum', 10000]]; const fam = { fashion: ['Men', 'Women', 'Shoes', 'Accessories'], beauty: ['Skincare', 'Makeup'], tech: ['Audio', 'Wearables'] };
export default function Rewards() {
  const { user, notify, refreshPoints } = useApp(); const pts = user?.loyaltyPoints || 0; const life = user?.lifetime ?? pts; const [tab, setTab] = useState('Overview'); const [code, setCode] = useState(''); const [orders, setOrders] = useState([]);
  useEffect(() => { if (user) { refreshPoints(); api.get('/orders').then((r) => setOrders(r.data.filter((o) => o.status !== 'Cancelled'))).catch(() => {}); } }, []);
  const cats = orders.flatMap((o) => o.items.map((i) => i.category)); const has = (k) => cats.some((c) => fam[k].includes(c)); const n = orders.length;
  const badges = [['', 'First Purchase', n >= 1], ['', '5 Orders', n >= 5], ['', '10 Orders', n >= 10], ['', 'Point Collector', life >= 1000], ['', 'Fashion Explorer', has('fashion')], ['', 'Beauty Lover', has('beauty')], ['', 'Tech Explorer', has('tech')]];
  const idx = LV.reduce((a, [, t], i) => (life >= t ? i : a), 0); const next = LV[idx + 1]; const pct = next ? Math.min(100, ((life - LV[idx][1]) / (next[1] - LV[idx][1])) * 100) : 100;
  const redeem = async (id) => { try { const { data } = await api.post('/points/redeem', { rewardId: id }); setCode(data.code); await refreshPoints(); notify('Reward redeemed!'); } catch (e) { notify(errMsg(e), 'err'); } };
  return (<div className="wrap sec"><div className="rhero"><div><small>Your Loyalty Points</small><h1>{pts.toLocaleString('en-IN')} Points</h1>{user ? <div className="row"><Link to="/wallet" className="btn light">View History</Link><Link to="/coupons" className="btn light">My Coupons</Link></div> : <Link to="/login" className="btn light">Sign in to see points</Link>}</div><div className="gift"></div></div>
    <div className="tabs mt">{['Overview', 'Redeem', 'Badges'].map((t) => <button key={t} className={tab === t ? 'on' : ''} onClick={() => setTab(t)}>{t}</button>)}</div>
    {code && <div className="card" style={{ background: '#ecfdf5' }}>Your coupon code: <b>{code}</b>. Find it in <Link to="/coupons">My Coupons</Link> to use it or send it to a friend.</div>}
    {tab === 'Overview' && <div className="card"><h3>Your Progress</h3><p className="muted mt">{LV[idx][0]} Member · {life.toLocaleString('en-IN')} lifetime points</p><div className="bar2"><i style={{ width: pct + '%' }} /></div><small className="muted">{next ? `${next[1] - life} points to ${next[0]}${next[0] === 'Silver' ? ' (5% bonus points)' : next[0] === 'Gold' ? ' (10% bonus points)' : ' (20% bonus points)'}` : 'Top tier reached '}</small>
      <p className="muted mt">Earn 10 points per ₹100 spent. 10 points = ₹1 off at checkout. Cancelled orders reverse earned points.</p></div>}
    {tab === 'Redeem' && <div className="grid g4">{R.map(([id, t, d, c, ic]) => <div key={id} className="card rw"><span className="mono">{ic}</span><h3>{t}</h3><p className="muted">{d}</p><b>{c} Points</b><button className="btn full" disabled={!user || pts < c} onClick={() => redeem(id)}>{!user ? 'Sign in' : pts >= c ? 'Redeem' : `Need ${c - pts} more points`}</button></div>)}</div>}
    {tab === 'Badges' && <div className="grid g4">{badges.map(([ic, t, on]) => <div key={t} className="card rw" style={{ opacity: on ? 1 : 0.45 }}><span className="mono">{t[0]}</span><b>{t}</b><small className={on ? 'ok' : 'muted'}>{on ? 'Unlocked' : 'Locked'}</small></div>)}</div>}</div>);
}
